dist: xenial
language: python
matrix:
  include:
    - python: 3.5
      env: TOXENV=py35-django-22
    - python: 3.6
      env: TOXENV=py36-django-22
    - python: 3.6
      env: TOXENV=py36-django-30
    - python: 3.6
      env: TOXENV=py36-django-31
    - python: 3.6
      env: TOXENV=py36-django-master
    - python: 3.7
      env: TOXENV=py37-django-22
    - python: 3.7
      env: TOXENV=py37-django-30
    - python: 3.7
      env: TOXENV=py37-django-31
    - python: 3.7
      env: TOXENV=py37-django-master
    - python: 3.8
      env: TOXENV=py38-django-22
    - python: 3.8
      env: TOXENV=py38-django-30
    - python: 3.8
      env: TOXENV=py38-django-31
    - python: 3.8
      env: TOXENV=py38-django-master
  allow_failures:
    - env: TOXENV=py36-django-master
    - env: TOXENV=py37-django-master
    - env: TOXENV=py38-django-master
install:
- pip install tox
script:
- tox
